Repository beyond-io/roo.me, pull requests merged in 2021-05, with the labels that each got.

#155 Add homepage base design
  main/templates/main/home.html
Labels: enhancement

#185 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#168 Adding messages display to the web pages- DO NOT MERGE BEFORE #172
  apartments/views.py
  main/templates/main/base_template.html
  main/templates/main/landing_page.html
  seekers/views.py
Labels: PR Dependent

#177 Adding 'accept connection' and 'reject connection' options
  contacts/models.py
  contacts/templates/contacts/contact-page-owner.html
  contacts/templates/contacts/contact-page-seeker.html
  contacts/tests.py
  contacts/urls.py
  contacts/views.py
Labels: PR dependent

#181 Add user-to-user matching algorithm
  apartments/models.py
  seekers/models.py
  users/models.py
Labels: enhancement

#184 Add seeker homepage
  main/static/img/user-account.png
  main/views.py
  seekers/templates/seekers/seeker_home.html
  seekers/views.py
Labels: PR dependent, enhancement

#234 Matching all forms to a convention
  apartments/forms.py
  apartments/templates/apartments/apartment_register.html
  main/templates/main/login.html
  search/forms.py
  search/templates/search/search.html
  seekers/forms.py
  seekers/templates/seekers/seeker_register.html
  seekers/templates/seekers/update-seeker.html
  users/templates/users/update.html
Labels: enhancement

#255 Add preferences and connected users filter to homepage search
  seekers/models.py
Labels: fix

#257 Add logout button to navbar template
  main/templates/main/base_template.html
Labels: enhancement, fix

#261 Fixed visual bug in the login page
  main/templates/main/login.html
Labels: fix

#271 fixed small typo
  seekers/models.py
Labels: fix

#273 Redesign card views
  apartments/templates/apartments/owner-homepage.html
  seekers/templates/seekers/seeker_home.html
Labels: enhancement

#276 Fix owners can connect owners
  apartments/templates/apartments/apartment-details.html
  apartments/templates/apartments/owner-homepage.html
  search/templates/search/search.html
Labels: fix

#286 roo.me README file
  README.md
Labels: documentation, enhancement
